### ISSUE TITLE
RGBA frames with Encoder?

### ISSUE THREAD

**Issue by sprajagopal** [image-rs/image-gif#88]
I tried both image-rs and this crate. I understand that image-rs simply provides an interface for this crate. But surprisingly image-rs supports RGBA frames in GifEncoder while this crate doesn't mention RGBA. Did I miss something?

NOTE: I couldn't use image-rs because it doesn't expose infinite loop functionality.

**Comment by HeroicKatora** [comment]
The `image` crate is a proxy for a combination of https://docs.rs/gif/0.11.1/gif/struct.Frame.html#method.from_rgba and https://docs.rs/gif/0.11.1/gif/struct.Encoder.html#method.write_frame .

That said, you should be cautious since `gif` only differentiates between fully opaque and fully transparent pixels. It's not possible to store a proper alpha channel. I'd advise using a newer format such as apng, webm or av1 if there are no backwards compatibility concerns.

**Comment by sprajagopal** [comment]
Got it! That makes sense. I tried the `from_rgba` method. Is the alpha channel in this supposed to be from 0 to 255?

**Comment by HeroicKatora** [comment]
It's supposed to be `0` _or_ `255`, yes. In particular it will reinterpret all non-zero values as `255`.
